// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:rick_morty_flutter_app/config/consts/environment.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions android = FirebaseOptions(
    apiKey: Environment.androidApiKey,
    appId: '1:1072811015171:android:72f40fb035361c6ea3e236',
    messagingSenderId: '1072811015171',
    projectId: 'rickmortyflutterapp',
    storageBucket: 'rickmortyflutterapp.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: Environment.iosApiKey,
    appId: '1:1072811015171:ios:ebdebf44d9fde881a3e236',
    messagingSenderId: '1072811015171',
    projectId: 'rickmortyflutterapp',
    storageBucket: 'rickmortyflutterapp.appspot.com',
    iosClientId:
        '1072811015171-9kofl186nqu4pikuq4qne3r6255e92bi.apps.googleusercontent.com',
    iosBundleId: 'com.roberdev.rickmorty.app',
  );
}
